/*
 * Checks each typed AES payload against its public array contract.
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem/gemd.h"
#include <string.h>

int gem_aes_validate(const gem_aes_packet_t *p)
{
    size_t used = 0;
    for (int i = 0; i < GEM_AES_ARGS; ++i) {
        if (p->counts[i] > GEM_AES_WORDS - used)
            return 0;
        used += p->counts[i];
    }
    switch (p->function) {
        case rpc_appl_find:
            if (!p->counts[0] || p->counts[0] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[0] * 2u))
                return 0;
            return 1;
        case rpc_appl_bvset:
            return 1;
        case rpc_appl_write:
            if ((8) < 0 || p->counts[2] != (8))
                return 0;
            return 1;
        case rpc_appl_read:
            if ((8) < 0 || p->counts[2] != (8))
                return 0;
            return 1;
        case rpc_appl_tplay:
            if (((int)p->args[1]) < 0 || p->counts[0] != ((int)p->args[1]))
                return 0;
            return 1;
        case rpc_appl_trecord:
            if (((int)p->args[1]) < 0 || p->counts[0] != ((int)p->args[1]))
                return 0;
            return 1;
        case rpc_appl_yield:
            return 1;
        case rpc_evnt_dclick:
            return 1;
        case rpc_menu_register:
            if (!p->counts[1] || p->counts[1] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[1] * 2u))
                return 0;
            return 1;
        case rpc_menu_unregister:
            return 1;
        case rpc_form_dial:
            return 1;
        case rpc_form_error:
            return 1;
        case rpc_graf_rubbox:
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            return 1;
        case rpc_graf_dragbox:
            if ((1) < 0 || p->counts[8] != (1))
                return 0;
            if ((1) < 0 || p->counts[9] != (1))
                return 0;
            return 1;
        case rpc_graf_mbox:
            return 1;
        case rpc_graf_growbox:
            return 1;
        case rpc_graf_shrinkbox:
            return 1;
        case rpc_scrp_clear:
            return 1;
        case rpc_shel_read:
            if ((260) < 0 || p->counts[0] != ((260) + 1) / 2)
                return 0;
            if ((260) < 0 || p->counts[1] != ((260) + 1) / 2)
                return 0;
            return 1;
        case rpc_shel_write:
            if (!p->counts[3] || p->counts[3] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[3] * 2u))
                return 0;
            if (!p->counts[4] || p->counts[4] > 1024 ||
                !memchr(p->data + (p->counts[3]), 0, p->counts[4] * 2u))
                return 0;
            return 1;
        case rpc_shel_get:
            if (((int)p->args[1]) < 0 ||
                p->counts[0] != (((int)p->args[1]) + 1) / 2)
                return 0;
            return 1;
        case rpc_shel_put:
            if (((int)p->args[1]) < 0 ||
                p->counts[0] != (((int)p->args[1]) + 1) / 2)
                return 0;
            return 1;
        case rpc_shel_rdef:
            if ((260) < 0 || p->counts[0] != ((260) + 1) / 2)
                return 0;
            if ((260) < 0 || p->counts[1] != ((260) + 1) / 2)
                return 0;
            return 1;
        case rpc_shel_wdef:
            if (!p->counts[0] || p->counts[0] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[0] * 2u))
                return 0;
            if (!p->counts[1] || p->counts[1] > 1024 ||
                !memchr(p->data + (p->counts[0]), 0, p->counts[1] * 2u))
                return 0;
            return 1;
        default:
            return 0;
    }
}

int gem_aes_draws(uint16_t function)
{
    switch (function) {
        default:
            return 0;
    }
}
