/*
 * Marshals typed AES scalar, array and string calls.
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD menu_register(WORD pid, char *pstr)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_menu_register};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = pid;
    size_t n1 = pstr ? strlen((const char *)pstr) + 1 : 1;
    n1 = (n1 + 1) / 2;
    if (n1 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (pstr)
        memcpy(packet.data + used, pstr, strlen((const char *)pstr) + 1);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD menu_unregister(WORD mid)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_menu_unregister};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = mid;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD form_dial(WORD flag, WORD x1, WORD y1, WORD w1, WORD h1, WORD x2, WORD y2,
               WORD w2, WORD h2)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_form_dial};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = flag;
    packet.args[1] = x1;
    packet.args[2] = y1;
    packet.args[3] = w1;
    packet.args[4] = h1;
    packet.args[5] = x2;
    packet.args[6] = y2;
    packet.args[7] = w2;
    packet.args[8] = h2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD form_error(WORD errnum)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_form_error};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = errnum;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD graf_rubbox(WORD xorigin, WORD yorigin, WORD wmin, WORD hmin, WORD *pwend,
                 WORD *phend)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_graf_rubbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = xorigin;
    packet.args[1] = yorigin;
    packet.args[2] = wmin;
    packet.args[3] = hmin;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (pwend)
        memcpy(pwend, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (phend)
        memcpy(phend, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}

WORD graf_dragbox(WORD w, WORD h, WORD sx, WORD sy, WORD xc, WORD yc, WORD wc,
                  WORD hc, WORD *pdx, WORD *pdy)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_graf_dragbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = w;
    packet.args[1] = h;
    packet.args[2] = sx;
    packet.args[3] = sy;
    packet.args[4] = xc;
    packet.args[5] = yc;
    packet.args[6] = wc;
    packet.args[7] = hc;
    int n8 = 1;
    if (n8 < 0 || (size_t)n8 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[8] = (uint16_t)n8;
    used += (size_t)n8;
    int n9 = 1;
    if (n9 < 0 || (size_t)n9 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[9] = (uint16_t)n9;
    used += (size_t)n9;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (pdx)
        memcpy(pdx, packet.data + used, (size_t)n8 * 2);
    used += packet.counts[8];
    if (pdy)
        memcpy(pdy, packet.data + used, (size_t)n9 * 2);
    used += packet.counts[9];
    (void)used;
    return (WORD)result;
}

WORD graf_mbox(WORD w, WORD h, WORD srcx, WORD srcy, WORD dstx, WORD dsty)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_graf_mbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = w;
    packet.args[1] = h;
    packet.args[2] = srcx;
    packet.args[3] = srcy;
    packet.args[4] = dstx;
    packet.args[5] = dsty;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD graf_growbox(WORD x1, WORD y1, WORD w1, WORD h1, WORD x2, WORD y2, WORD w2,
                  WORD h2)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_graf_growbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = x1;
    packet.args[1] = y1;
    packet.args[2] = w1;
    packet.args[3] = h1;
    packet.args[4] = x2;
    packet.args[5] = y2;
    packet.args[6] = w2;
    packet.args[7] = h2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
