/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD v_meta_extents(WORD handle, WORD min_x, WORD min_y, WORD max_x, WORD max_y)
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_v_meta_extents};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = min_x;
    packet.args[2] = min_y;
    packet.args[3] = max_x;
    packet.args[4] = max_y;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_write_meta(WORD handle, WORD num_intin, WORD *intin, WORD num_ptsin,
                  WORD *ptsin)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_write_meta};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = num_intin;
    int n2 = num_intin;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    if (intin)
        memcpy(packet.data + used, intin, (size_t)n2 * 2);
    used += (size_t)n2;
    packet.args[3] = num_ptsin;
    int n4 = 2 * num_ptsin;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    if (ptsin)
        memcpy(packet.data + used, ptsin, (size_t)n4 * 2);
    used += (size_t)n4;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[2];
    used += packet.counts[4];
    (void)used;
    return (WORD)result;
}

WORD vm_filename(WORD handle, BYTE *filename)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vm_filename};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    size_t n1 = filename ? strlen((const char *)filename) + 1 : 1;
    n1 = (n1 + 1) / 2;
    if (n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (filename)
        memcpy(packet.data + used, filename,
               strlen((const char *)filename) + 1);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD v_get_pixel(WORD handle, WORD x, WORD y, WORD *pel, WORD *index)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_get_pixel};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (pel)
        memcpy(pel, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (index)
        memcpy(index, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    (void)used;
    return (WORD)result;
}

WORD v_escape(WORD handle, WORD function, WORD count_in, WORD count_out,
              WORD *intin, WORD *ptsout)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_escape};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = function;
    packet.args[2] = count_in;
    packet.args[3] = count_out;
    int n4 = count_in;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    if (intin)
        memcpy(packet.data + used, intin, (size_t)n4 * 2);
    used += (size_t)n4;
    int n5 = 2 * count_out;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[4];
    if (ptsout)
        memcpy(ptsout, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}
