/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

VOID v_pmarker(WORD handle, WORD count, WORD xy[])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_pmarker};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = count;
    int n2 = 2 * count;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return;
    packet.counts[2] = (uint16_t)n2;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n2 * 2);
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    used += packet.counts[2];
    (void)used;
}

WORD v_cellarray(WORD handle, WORD xy[], WORD row_length, WORD el_per_row,
                 WORD num_rows, WORD wr_mode, WORD colors[])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_cellarray};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n1 * 2);
    used += (size_t)n1;
    packet.args[2] = row_length;
    packet.args[3] = el_per_row;
    packet.args[4] = num_rows;
    packet.args[5] = wr_mode;
    int n6 = el_per_row * num_rows;
    if (n6 < 0 || (size_t)n6 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[6] = (uint16_t)n6;
    if (colors)
        memcpy(packet.data + used, colors, (size_t)n6 * 2);
    used += (size_t)n6;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    used += packet.counts[6];
    (void)used;
    return (WORD)result;
}

VOID v_arc(WORD handle, WORD x, WORD y, WORD radius, WORD begang, WORD endang)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_arc};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = radius;
    packet.args[4] = begang;
    packet.args[5] = endang;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_pieslice(WORD handle, WORD x, WORD y, WORD radius, WORD begang,
                WORD endang)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_pieslice};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = radius;
    packet.args[4] = begang;
    packet.args[5] = endang;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_pie(WORD handle, WORD x, WORD y, WORD radius, WORD begang, WORD endang)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_pie};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = radius;
    packet.args[4] = begang;
    packet.args[5] = endang;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_circle(WORD handle, WORD x, WORD y, WORD radius)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_circle};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = radius;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_ellipse(WORD handle, WORD x, WORD y, WORD xrad, WORD yrad)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_ellipse};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = xrad;
    packet.args[4] = yrad;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_ellarc(WORD handle, WORD x, WORD y, WORD xrad, WORD yrad, WORD begang,
              WORD endang)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_ellarc};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = xrad;
    packet.args[4] = yrad;
    packet.args[5] = begang;
    packet.args[6] = endang;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}
