/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

VOID v_ellpie(WORD handle, WORD x, WORD y, WORD xrad, WORD yrad, WORD begang,
              WORD endang)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_ellpie};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = xrad;
    packet.args[4] = yrad;
    packet.args[5] = begang;
    packet.args[6] = endang;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

VOID v_rfbox(WORD handle, WORD xy[4])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_rfbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return;
    packet.counts[1] = (uint16_t)n1;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n1 * 2);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    used += packet.counts[1];
    (void)used;
}

VOID v_justified(WORD handle, WORD x, WORD y, char *string, WORD length,
                 WORD wordspace, WORD charspace)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_justified};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    size_t n3 = string ? strlen((const char *)string) + 1 : 1;
    n3 = (n3 + 1) / 2;
    if (n3 > GEM_VDI_WORDS - used)
        return;
    packet.counts[3] = (uint16_t)n3;
    if (string)
        memcpy(packet.data + used, string, strlen((const char *)string) + 1);
    used += (size_t)n3;
    packet.args[4] = length;
    packet.args[5] = wordspace;
    packet.args[6] = charspace;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    used += packet.counts[3];
    (void)used;
}

WORD vst_height(WORD handle, WORD height, WORD *charw, WORD *charh, WORD *cellw,
                WORD *cellh)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vst_height};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = height;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (charw)
        memcpy(charw, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (charh)
        memcpy(charh, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (cellw)
        memcpy(cellw, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (cellh)
        memcpy(cellh, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}

WORD vst_rotation(WORD handle, WORD angle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vst_rotation};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = angle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vs_color(WORD handle, WORD index, WORD rgb[3])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vs_color};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = index;
    int n2 = 3;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    if (rgb)
        memcpy(packet.data + used, rgb, (size_t)n2 * 2);
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD vsm_type(WORD handle, WORD symbol)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_type};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = symbol;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vsm_height(WORD handle, WORD height)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_height};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = height;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
