/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD v_eeos(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_eeos};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_eeol(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_eeol};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vs_curaddress(WORD handle, WORD row, WORD column)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vs_curaddress};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = row;
    packet.args[2] = column;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curtext(WORD handle, BYTE *string)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curtext};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    size_t n1 = string ? strlen((const char *)string) + 1 : 1;
    n1 = (n1 + 1) / 2;
    if (n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (string)
        memcpy(packet.data + used, string, strlen((const char *)string) + 1);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD v_rvon(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_rvon};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_rvoff(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_rvoff};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vq_curaddress(WORD handle, WORD *row, WORD *column)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_curaddress};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 1;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (row)
        memcpy(row, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    if (column)
        memcpy(column, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD vq_tabstatus(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_tabstatus};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
