/*
 * Marshals typed AES scalar, array and string calls.
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD graf_shrinkbox(WORD x1, WORD y1, WORD w1, WORD h1, WORD x2, WORD y2,
                    WORD w2, WORD h2)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_graf_shrinkbox};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = x1;
    packet.args[1] = y1;
    packet.args[2] = w1;
    packet.args[3] = h1;
    packet.args[4] = x2;
    packet.args[5] = y2;
    packet.args[6] = w2;
    packet.args[7] = h2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD scrp_clear(void)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_scrp_clear};
    int32_t result = 0;
    size_t used = 0;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD shel_read(char *cmd, char *tail)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_read};
    int32_t result = 0;
    size_t used = 0;
    int n0 = (260 + 1) / 2;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    used += (size_t)n0;
    int n1 = (260 + 1) / 2;
    if (n1 < 0 || (size_t)n1 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (cmd)
        memcpy(cmd, packet.data + used,
               strlen((const char *)(packet.data + used)) + 1);
    used += packet.counts[0];
    if (tail)
        memcpy(tail, packet.data + used,
               strlen((const char *)(packet.data + used)) + 1);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD shel_write(WORD doex, WORD isgr, WORD iscr, char *cmd, char *tail)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_write};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = doex;
    packet.args[1] = isgr;
    packet.args[2] = iscr;
    size_t n3 = cmd ? strlen((const char *)cmd) + 1 : 1;
    n3 = (n3 + 1) / 2;
    if (n3 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    if (cmd)
        memcpy(packet.data + used, cmd, strlen((const char *)cmd) + 1);
    used += (size_t)n3;
    size_t n4 = tail ? strlen((const char *)tail) + 1 : 1;
    n4 = (n4 + 1) / 2;
    if (n4 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    if (tail)
        memcpy(packet.data + used, tail, strlen((const char *)tail) + 1);
    used += (size_t)n4;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[3];
    used += packet.counts[4];
    (void)used;
    return (WORD)result;
}

WORD shel_get(char *buf, WORD length)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_get};
    int32_t result = 0;
    size_t used = 0;
    int n0 = (length + 1) / 2;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    used += (size_t)n0;
    packet.args[1] = length;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (buf)
        memcpy(buf, packet.data + used, length);
    used += packet.counts[0];
    (void)used;
    return (WORD)result;
}

WORD shel_put(char *buf, WORD length)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_put};
    int32_t result = 0;
    size_t used = 0;
    int n0 = (length + 1) / 2;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    if (buf)
        memcpy(packet.data + used, buf, length);
    used += (size_t)n0;
    packet.args[1] = length;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[0];
    (void)used;
    return (WORD)result;
}

WORD shel_rdef(char *lpcmd, char *lpdir)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_rdef};
    int32_t result = 0;
    size_t used = 0;
    int n0 = (260 + 1) / 2;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    used += (size_t)n0;
    int n1 = (260 + 1) / 2;
    if (n1 < 0 || (size_t)n1 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (lpcmd)
        memcpy(lpcmd, packet.data + used,
               strlen((const char *)(packet.data + used)) + 1);
    used += packet.counts[0];
    if (lpdir)
        memcpy(lpdir, packet.data + used,
               strlen((const char *)(packet.data + used)) + 1);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD shel_wdef(char *lpcmd, char *lpdir)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_shel_wdef};
    int32_t result = 0;
    size_t used = 0;
    size_t n0 = lpcmd ? strlen((const char *)lpcmd) + 1 : 1;
    n0 = (n0 + 1) / 2;
    if (n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    if (lpcmd)
        memcpy(packet.data + used, lpcmd, strlen((const char *)lpcmd) + 1);
    used += (size_t)n0;
    size_t n1 = lpdir ? strlen((const char *)lpdir) + 1 : 1;
    n1 = (n1 + 1) / 2;
    if (n1 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (lpdir)
        memcpy(packet.data + used, lpdir, strlen((const char *)lpdir) + 1);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[0];
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}
