/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD vsm_color(WORD handle, WORD color_index)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_color};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = color_index;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vq_color(WORD handle, WORD index, WORD setflag, WORD rgb[])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_color};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = index;
    packet.args[2] = setflag;
    int n3 = 3;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (rgb)
        memcpy(rgb, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    (void)used;
    return (WORD)result;
}

WORD vq_cellarray(WORD handle, WORD xy[], WORD row_length, WORD num_requested,
                  WORD *el_used, WORD *rows_used, WORD status[])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_cellarray};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n1 * 2);
    used += (size_t)n1;
    packet.args[2] = row_length;
    packet.args[3] = num_requested;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    int n6 = num_requested;
    if (n6 < 0 || (size_t)n6 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[6] = (uint16_t)n6;
    used += (size_t)n6;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    if (el_used)
        memcpy(el_used, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (rows_used)
        memcpy(rows_used, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    if (status)
        memcpy(status, packet.data + used, (size_t)n6 * 2);
    used += packet.counts[6];
    (void)used;
    return (WORD)result;
}

WORD vrq_locator(WORD handle, WORD x, WORD y, WORD *xout, WORD *yout,
                 WORD *term)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vrq_locator};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (xout)
        memcpy(xout, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (yout)
        memcpy(yout, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (term)
        memcpy(term, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}

WORD vsm_locator(WORD handle, WORD x, WORD y, WORD *xout, WORD *yout,
                 WORD *term)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_locator};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (xout)
        memcpy(xout, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (yout)
        memcpy(yout, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (term)
        memcpy(term, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}

WORD vrq_valuator(WORD handle, WORD val_in, WORD *val_out, WORD *term)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vrq_valuator};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = val_in;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (val_out)
        memcpy(val_out, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (term)
        memcpy(term, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    (void)used;
    return (WORD)result;
}

WORD vsm_valuator(WORD handle, WORD val_in, WORD *val_out, WORD *term)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_valuator};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = val_in;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (val_out)
        memcpy(val_out, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (term)
        memcpy(term, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    (void)used;
    return (WORD)result;
}

WORD vrq_choice(WORD handle, WORD ch_in, WORD *ch_out)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vrq_choice};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = ch_in;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (ch_out)
        memcpy(ch_out, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}
