/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD v_hardcopy(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_hardcopy};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_dspcur(WORD handle, WORD x, WORD y)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_dspcur};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_rmcur(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_rmcur};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_form_adv(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_form_adv};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_output_window(WORD handle, WORD xy[4])
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_v_output_window};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n1 * 2);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD v_clear_disp_list(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_v_clear_disp_list};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_bit_image(WORD handle, BYTE *filename, WORD aspect, WORD x_scale,
                 WORD y_scale, WORD h_align, WORD v_align, WORD xy[4])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_bit_image};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    size_t n1 = filename ? strlen((const char *)filename) + 1 : 1;
    n1 = (n1 + 1) / 2;
    if (n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (filename)
        memcpy(packet.data + used, filename,
               strlen((const char *)filename) + 1);
    used += (size_t)n1;
    packet.args[2] = aspect;
    packet.args[3] = x_scale;
    packet.args[4] = y_scale;
    packet.args[5] = h_align;
    packet.args[6] = v_align;
    int n7 = 4;
    if (n7 < 0 || (size_t)n7 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[7] = (uint16_t)n7;
    if (xy)
        memcpy(packet.data + used, xy, (size_t)n7 * 2);
    used += (size_t)n7;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    used += packet.counts[7];
    (void)used;
    return (WORD)result;
}

WORD vs_palette(WORD handle, WORD palette)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vs_palette};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = palette;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
