/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD vsl_udsty(WORD handle, WORD pattern)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsl_udsty};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = pattern;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vqin_mode(WORD handle, WORD dev_type, WORD *input_mode)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vqin_mode};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = dev_type;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (input_mode)
        memcpy(input_mode, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD vqt_width(WORD handle, WORD character, WORD *cell_width, WORD *left_delta,
               WORD *right_delta)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vqt_width};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = character;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (cell_width)
        memcpy(cell_width, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (left_delta)
        memcpy(left_delta, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (right_delta)
        memcpy(right_delta, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    (void)used;
    return (WORD)result;
}

WORD vst_load_fonts(WORD handle, WORD select)
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vst_load_fonts};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = select;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vst_unload_fonts(WORD handle, WORD select)
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vst_unload_fonts};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = select;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

VOID vq_mouse(VDI_HANDLE handle, WORD *status, WORD *x, WORD *y)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_mouse};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 1;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    if (status)
        memcpy(status, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    if (x)
        memcpy(x, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (y)
        memcpy(y, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    (void)used;
}

WORD vq_key_s(WORD handle, WORD *status)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_key_s};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 1;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (status)
        memcpy(status, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vqt_name(WORD handle, WORD element_num, BYTE *name)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vqt_name};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = element_num;
    int n2 = (33 + 1) / 2;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (name)
        memcpy(name, packet.data + used, 33);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}
