/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD vsm_choice(WORD handle, WORD *choice)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsm_choice};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 1;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (choice)
        memcpy(choice, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vsin_mode(WORD handle, WORD dev_type, WORD mode)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsin_mode};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = dev_type;
    packet.args[2] = mode;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vql_attributes(WORD handle, WORD attrib[])
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vql_attributes};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (attrib)
        memcpy(attrib, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vqm_attributes(WORD handle, WORD attrib[])
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vqm_attributes};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (attrib)
        memcpy(attrib, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vqf_attributes(WORD handle, WORD attrib[])
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vqf_attributes};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 4;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (attrib)
        memcpy(attrib, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vqt_attributes(WORD handle, WORD attrib[])
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vqt_attributes};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 6;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (attrib)
        memcpy(attrib, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vst_alignment(WORD handle, WORD horiz, WORD vert)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vst_alignment};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = horiz;
    packet.args[2] = vert;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vq_extnd(WORD handle, WORD owflag, WORD work_out[])
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_extnd};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = owflag;
    int n2 = 57;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (work_out)
        memcpy(work_out, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}
