/*
 * Marshals typed AES scalar, array and string calls.
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD appl_find(char *name)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_find};
    int32_t result = 0;
    size_t used = 0;
    size_t n0 = name ? strlen((const char *)name) + 1 : 1;
    n0 = (n0 + 1) / 2;
    if (n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    if (name)
        memcpy(packet.data + used, name, strlen((const char *)name) + 1);
    used += (size_t)n0;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[0];
    (void)used;
    return (WORD)result;
}

WORD appl_bvset(WORD bvdisk, WORD bvhard)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_bvset};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = bvdisk;
    packet.args[1] = bvhard;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD appl_write(WORD rwid, WORD length, void *pbuff)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_write};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = rwid;
    packet.args[1] = length;
    int n2 = 8;
    if (n2 < 0 || (size_t)n2 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    if (pbuff)
        memcpy(packet.data + used, pbuff, (size_t)n2 * 2);
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD appl_read(WORD ap_rwid, WORD ap_rlength, void *ap_rpbuff)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_read};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = ap_rwid;
    packet.args[1] = ap_rlength;
    int n2 = 8;
    if (n2 < 0 || (size_t)n2 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (ap_rpbuff)
        memcpy(ap_rpbuff, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD appl_tplay(void *pbuff, WORD length, WORD scale)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_tplay};
    int32_t result = 0;
    size_t used = 0;
    int n0 = length;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    if (pbuff)
        memcpy(packet.data + used, pbuff, (size_t)n0 * 2);
    used += (size_t)n0;
    packet.args[1] = length;
    packet.args[2] = scale;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[0];
    (void)used;
    return (WORD)result;
}

WORD appl_trecord(void *pbuff, WORD length)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_trecord};
    int32_t result = 0;
    size_t used = 0;
    int n0 = length;
    if (n0 < 0 || (size_t)n0 > GEM_AES_WORDS - used)
        return 0;
    packet.counts[0] = (uint16_t)n0;
    used += (size_t)n0;
    packet.args[1] = length;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (pbuff)
        memcpy(pbuff, packet.data + used, (size_t)n0 * 2);
    used += packet.counts[0];
    (void)used;
    return (WORD)result;
}

WORD appl_yield(void)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_appl_yield};
    int32_t result = 0;
    size_t used = 0;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD evnt_dclick(WORD clicks, WORD setget)
{
    gem_aes_packet_t packet = {.handle = 0, .function = rpc_evnt_dclick};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = clicks;
    packet.args[1] = setget;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
