/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

VOID v_contourfill(WORD handle, WORD x, WORD y, WORD index)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_contourfill};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = x;
    packet.args[2] = y;
    packet.args[3] = index;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return;
    used = 0;
    (void)used;
}

WORD vst_background(WORD handle, WORD mode)
{
    gem_vdi_packet_t packet = {.handle = handle,
                               .function = rpc_vst_background};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = mode;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vst_effects(WORD handle, WORD effect)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vst_effects};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = effect;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vst_point(WORD handle, WORD point, WORD *charw, WORD *charh, WORD *cellw,
               WORD *cellh)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vst_point};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = point;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    int n3 = 1;
    if (n3 < 0 || (size_t)n3 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[3] = (uint16_t)n3;
    used += (size_t)n3;
    int n4 = 1;
    if (n4 < 0 || (size_t)n4 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[4] = (uint16_t)n4;
    used += (size_t)n4;
    int n5 = 1;
    if (n5 < 0 || (size_t)n5 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[5] = (uint16_t)n5;
    used += (size_t)n5;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (charw)
        memcpy(charw, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    if (charh)
        memcpy(charh, packet.data + used, (size_t)n3 * 2);
    used += packet.counts[3];
    if (cellw)
        memcpy(cellw, packet.data + used, (size_t)n4 * 2);
    used += packet.counts[4];
    if (cellh)
        memcpy(cellh, packet.data + used, (size_t)n5 * 2);
    used += packet.counts[5];
    (void)used;
    return (WORD)result;
}

WORD vsl_ends(WORD handle, WORD begstyle, WORD endstyle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsl_ends};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = begstyle;
    packet.args[2] = endstyle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vsl_end_style(WORD handle, WORD begstyle, WORD endstyle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsl_end_style};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    packet.args[1] = begstyle;
    packet.args[2] = endstyle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD vsc_form(WORD handle, MFORM *cur_form)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsc_form};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 37;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (cur_form)
        memcpy(packet.data + used, cur_form, (size_t)n1 * 2);
    used += (size_t)n1;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}

WORD vsf_udpat(WORD handle, WORD *fill_pat, WORD planes)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vsf_udpat};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 16;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    if (fill_pat)
        memcpy(packet.data + used, fill_pat, (size_t)n1 * 2);
    used += (size_t)n1;
    packet.args[2] = planes;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    used += packet.counts[1];
    (void)used;
    return (WORD)result;
}
