/*
 * Marshals typed VDI scalar, array and string calls.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem_protocol.h"
#include "gem/gemd.h"
#include <string.h>

WORD vq_chcells(WORD handle, WORD *rows, WORD *columns)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_vq_chcells};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    int n1 = 1;
    if (n1 < 0 || (size_t)n1 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[1] = (uint16_t)n1;
    used += (size_t)n1;
    int n2 = 1;
    if (n2 < 0 || (size_t)n2 > GEM_VDI_WORDS - used)
        return 0;
    packet.counts[2] = (uint16_t)n2;
    used += (size_t)n2;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    if (rows)
        memcpy(rows, packet.data + used, (size_t)n1 * 2);
    used += packet.counts[1];
    if (columns)
        memcpy(columns, packet.data + used, (size_t)n2 * 2);
    used += packet.counts[2];
    (void)used;
    return (WORD)result;
}

WORD v_exit_cur(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_exit_cur};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_enter_cur(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_enter_cur};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curup(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curup};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curdown(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curdown};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curright(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curright};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curleft(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curleft};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}

WORD v_curhome(WORD handle)
{
    gem_vdi_packet_t packet = {.handle = handle, .function = rpc_v_curhome};
    int32_t result = 0;
    size_t used = 0;
    packet.args[0] = handle;
    (void)used;
    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet), &result,
                      &packet, sizeof(packet)))
        return 0;
    used = 0;
    (void)used;
    return (WORD)result;
}
