#!/usr/bin/env python3
"""Generate typed VDI RPC wrappers from the public prototypes and size schema.

MIT License (see LICENSE). Copyright (C) 2026 tomaz stih.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[2]
header = re.sub(r'/\*.*?\*/', '', (root/'include/gem/vdi.h').read_text(), flags=re.S)
existing = '\n'.join((root/'src/gem'/p).read_text() for p in ['client.c','client_queries.c','client_objc.c'])
manual = {'v_opnwk','v_opnrwk','v_clswk','vro_cpyfm','vrt_cpyfm','vr_trnfm','vex_timv','vex_butv','vex_motv','vex_curv','vrq_string','vsm_string'}
# Pointer arguments: direction and element count. Counts reflect native VDI.
shape = {
 'v_pmarker': {'xy':('i','2*count')},
 'v_cellarray': {'xy':('i','4'),'colors':('i','el_per_row*num_rows')},
 'v_rbox': {'xy':('i','4')}, 'v_rfbox': {'xy':('i','4')},
 'v_justified': {'string':('s','0')},
 'vs_color': {'rgb':('i','3')}, 'vq_color': {'rgb':('o','3')},
 'vq_cellarray': {'xy':('i','4'),'status':('o','num_requested')},
 'vql_attributes': {'attrib':('o','4')}, 'vqm_attributes': {'attrib':('o','4')},
 'vqf_attributes': {'attrib':('o','4')}, 'vqt_attributes': {'attrib':('o','6')},
 'vq_extnd': {'work_out':('o','57')},
 'vsc_form': {'cur_form':('i','37')}, 'vsf_udpat': {'fill_pat':('i','16')},
 'vqt_name': {'name':('b','33')}, 'v_curtext': {'string':('s','0')},
 'v_output_window': {'xy':('i','4')},
 'v_bit_image': {'filename':('s','0'),'xy':('i','4')},
 'v_write_meta': {'intin':('i','num_intin'),'ptsin':('i','2*num_ptsin')},
 'vm_filename': {'filename':('s','0')},
 'v_escape': {'intin':('i','count_in'),'ptsout':('o','2*count_out')},
}
notice = '''/*
 * %s
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
'''
functions=[]
for ret,name,args in re.findall(r'\b(WORD|VOID)\s+(\w+)\s*\((.*?)\);',header,re.S):
 if name in manual or re.search(r'\b'+name+r'\s*\([^;]*?\)\s*\{',existing,re.S):continue
 params=[]
 for arg in args.split(','):
  arg=' '.join(arg.split()); pname=re.search(r'(\w+)\s*(?:\[[^]]*\])?$',arg)[1]
  pointer='*' in arg or '[' in arg
  direction,count=shape.get(name,{}).get(pname,('o','1')) if pointer else ('v','0')
  params.append((arg,pname,direction,count))
 functions.append((ret,name,params))
ids=['    rpc_'+name+' = '+str(i+1)+',' for i,(_,name,_) in enumerate(functions)]
h='''enum { GEM_VDI_WORDS = 2048, GEM_VDI_ARGS = 12 };
typedef struct gem_vdi_packet {
    WORD handle;
    uint16_t function;
    WORD args[GEM_VDI_ARGS];
    uint16_t counts[GEM_VDI_ARGS];
    WORD data[GEM_VDI_WORDS];
} gem_vdi_packet_t;
enum gem_vdi_function {
'''+ '\n'.join(ids)+ '\n};\n'
h+='''/* Validate sizes, array counts and terminated strings before dispatch. */
int gem_vdi_validate(const gem_vdi_packet_t *packet);
/* Execute a validated packet against the server workstation; copy outputs. */
WORD gem_vdi_dispatch(gem_vdi_packet_t *packet);
/* Return nonzero for operations that draw into the screen. */
int gem_vdi_draws(uint16_t function);
'''
destination = root/'include/gem/gemd.h'
begin = '/* BEGIN GENERATED VDI RPC */'
end = '/* END GENERATED VDI RPC */'
text = destination.read_text()
assert text.count(begin) == text.count(end) == 1, 'Missing generated section markers'
prefix, rest = text.split(begin, 1)
_, suffix = rest.split(end, 1)
destination.write_text(prefix + begin + '\n' + h.rstrip() + '\n' + end + suffix)
client=[];server=[];valid=[]
for ret,name,params in functions:
 c=[ret+' '+name+'('+', '.join(p[0] for p in params)+')','{',f'    gem_vdi_packet_t packet = {{.handle = handle, .function = rpc_{name}}};','    int32_t result = 0;','    size_t used = 0;']
 v=[f'    case rpc_{name}:'];d=[f'    case rpc_{name}: {{'];call=[];copy=[];offsets=[]
 for i,(arg,pname,direction,count) in enumerate(params):
  if direction=='v':
   c.append(f'    packet.args[{i}] = {pname};'); call.append(f'p->args[{i}]');continue
  offset=' + '.join(offsets) or '0'
  expr=count
  for j,(_,other,kind,_) in enumerate(params):
   if kind=='v': expr=re.sub(r'\b'+other+r'\b',f'(int)p->args[{j}]',expr)
  if direction=='s':
   c.append(f'    size_t n{i} = {pname} ? strlen((const char *){pname}) + 1 : 1;')
   c.append(f'    n{i} = (n{i} + 1) / 2;')
   v.append(f'        if (!p->counts[{i}] || p->counts[{i}] > 1024 || !memchr(p->data + ({offset}), 0, p->counts[{i}]*2u)) return 0;')
  else:
   c.append(f'    int n{i} = '+ (f'({count}+1)/2;' if direction=='b' else f'{count};'))
   v.append(f'        if (({expr}) < 0 || p->counts[{i}] != '+(f'(({expr})+1)/2' if direction=='b' else f'({expr})')+') return 0;')
  c.append(f'    if (n{i} < 0 || (size_t)n{i} > GEM_VDI_WORDS-used) '+('return;' if ret=='VOID' else 'return 0;')) if direction!='s' else c.append(f'    if (n{i} > GEM_VDI_WORDS-used) '+('return;' if ret=='VOID' else 'return 0;'))
  c.append(f'    packet.counts[{i}] = (uint16_t)n{i};')
  if direction in ['i','s']:
   size=f'strlen((const char *){pname})+1' if direction=='s' else f'(size_t)n{i}*2'
   c.append(f'    if ({pname}) memcpy(packet.data+used, {pname}, {size});')
  d.append(f'        void *arg{i} = p->data + ({offset});')
  offsets.append(f'p->counts[{i}]')
  call.append(f'arg{i}')
  if direction in ['o','b']:
   copy.append(f'    if ({pname}) memcpy({pname}, packet.data+used, '+(count if direction=='b' else f'(size_t)n{i}*2')+');')
  copy.append(f'    used += packet.counts[{i}];')
  c.append(f'    used += (size_t)n{i};')

 c += ['    (void)used;', '    if (!gem_rpc_call(GEM_RPC_VDI_EXT, &packet, sizeof(packet),', '            &result, &packet, sizeof(packet))) '+('return;' if ret=='VOID' else 'return 0;'),'    used = 0;']+copy+['    (void)used;']
 if ret=='WORD':c+=['    return (WORD)result;']
 c+=['}'];client.append('\n'.join(c))
 d += ['        '+('return ' if ret=='WORD' else '')+name+'('+', '.join(call)+');']
 if ret=='VOID':d+=['        return 1;']
 d+=['    }'];server+= '\n'.join(d)+'\n'
 v+=['        return 1;'];valid+='\n'.join(v)+'\n'
for i in range(0,len(client),8):
 (root/f'src/gem/client_vdi_{i//8}.c').write_text(notice%'Marshals typed VDI scalar, array and string calls.'+'#include "gem_protocol.h"\n#include "gem/gemd.h"\n#include <string.h>\n\n'+'\n\n'.join(client[i:i+8])+'\n')
(root/'src/gemd/vdi_dispatch.c').write_text(notice%'Executes validated VDI extension calls in the display server.'+'#include "gem/gemd.h"\n#include <stddef.h>\n\nWORD gem_vdi_dispatch(gem_vdi_packet_t *p)\n{\n    switch(p->function) {\n'+''.join(server)+'    default: return 0;\n    }\n}\n')
s=notice%'Checks each typed VDI payload against its public array contract.'+'#include "gem/gemd.h"\n#include <string.h>\n\nint gem_vdi_validate(const gem_vdi_packet_t *p)\n{\n    size_t used = 0;\n    for (int i=0; i<GEM_VDI_ARGS; ++i) {\n        if (p->counts[i] > GEM_VDI_WORDS-used) return 0;\n        used += p->counts[i];\n    }\n    if (p->args[0] != p->handle) return 0;\n    switch(p->function) {\n'+''.join(valid)+'    default: return 0;\n    }\n}\n'
draws={'v_pmarker','v_cellarray','v_arc','v_pieslice','v_pie','v_circle','v_ellipse','v_ellarc','v_ellpie','v_rbox','v_rfbox','v_justified','v_contourfill','v_curtext','v_eeos','v_eeol','v_clear_disp_list'}
s+='\nint gem_vdi_draws(uint16_t function)\n{\n    switch(function) {\n'+''.join(f'    case rpc_{n}:\n' for _,n,_ in functions if n in draws)+'        return 1;\n    default: return 0;\n    }\n}\n'
(root/'src/gem/vdi_validate.c').write_text(s)
print('Generated',len(functions),'VDI calls')
