#!/usr/bin/env python3
"""Generate typed AES RPC wrappers from the public prototypes and size schema.

MIT License (see LICENSE). Copyright (C) 2026 tomaz stih.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[2]
header = re.sub(r'/\*.*?\*/', '', (root/'include/gem/aes.h').read_text(), flags=re.S)
existing = '\n'.join(p.read_text() for p in (root/'src/gem').glob('client*.c') if not re.match(r'client_aes_\d+\.c',p.name))
manual = {'appl_init','appl_exit','evnt_keybd','evnt_button','evnt_mouse','evnt_timer',
 'menu_icheck','menu_ienable','menu_text','objc_delete','objc_order',
 'rsrc_load','rsrc_free','rsrc_gaddr','rsrc_saddr','rsrc_obfix','shel_find','shel_envrn'}
shape = {
 'appl_find': {'name':('s','0')},
 'appl_write': {'pbuff':('i','8')}, 'appl_read': {'ap_rpbuff':('o','8')},
 'appl_tplay': {'pbuff':('i','length')}, 'appl_trecord': {'pbuff':('o','length')},
 'menu_register': {'pstr':('s','0')},
 'shel_read': {'cmd':('b','260'),'tail':('b','260')},
 'shel_write': {'cmd':('s','0'),'tail':('s','0')},
 'shel_get': {'buf':('b','length')}, 'shel_put': {'buf':('j','length')},
 'shel_rdef': {'lpcmd':('b','260'),'lpdir':('b','260')},
 'shel_wdef': {'lpcmd':('s','0'),'lpdir':('s','0')},
}
notice = '''/*
 * %s
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
'''
functions=[]
for ret,name,args in re.findall(r'\b(WORD|VOID)\s+(\w+)\s*\((.*?)\);',header,re.S):
 if name in manual or re.search(r'\b'+name+r'\s*\([^;]*?\)\s*\{',existing,re.S):continue
 params=[]
 for arg in ([] if args.strip() in ('','void','VOID') else args.split(',')):
  arg=' '.join(arg.split()); pname=re.search(r'(\w+)\s*(?:\[[^]]*\])?$',arg)[1]
  pointer='*' in arg or '[' in arg
  direction,count=shape.get(name,{}).get(pname,('o','1')) if pointer else ('v','0')
  params.append((arg,pname,direction,count))
 functions.append((ret,name,params))
ids=['    rpc_'+name+' = '+str(i+1)+',' for i,(_,name,_) in enumerate(functions)]
h='''enum { GEM_AES_WORDS = 2048, GEM_AES_ARGS = 12 };
typedef struct gem_aes_packet {
    WORD handle;
    uint16_t function;
    WORD args[GEM_AES_ARGS];
    uint16_t counts[GEM_AES_ARGS];
    WORD data[GEM_AES_WORDS];
} gem_aes_packet_t;
enum gem_aes_function {
'''+ '\n'.join(ids)+ '\n};\n'
h+='''/* Validate sizes, array counts and terminated strings before dispatch. */
int gem_aes_validate(const gem_aes_packet_t *packet);
/* Execute a validated packet against the server workstation; copy outputs. */
WORD gem_aes_dispatch(gem_aes_packet_t *packet);
/* Return nonzero for operations that draw into the screen. */
int gem_aes_draws(uint16_t function);
'''
destination = root/'include/gem/gemd.h'
begin = '/* BEGIN GENERATED AES RPC */'
end = '/* END GENERATED AES RPC */'
text = destination.read_text()
assert text.count(begin) == text.count(end) == 1, 'Missing generated section markers'
prefix, rest = text.split(begin, 1)
_, suffix = rest.split(end, 1)
destination.write_text(prefix + begin + '\n' + h.rstrip() + '\n' + end + suffix)
client=[];server=[];valid=[]
for ret,name,params in functions:
 c=[ret+' '+name+'('+(', '.join(p[0] for p in params) or 'void')+')','{',f'    gem_aes_packet_t packet = {{.handle = 0, .function = rpc_{name}}};','    int32_t result = 0;','    size_t used = 0;']
 v=[f'    case rpc_{name}:'];d=[f'    case rpc_{name}: {{'];call=[];copy=[];offsets=[]
 for i,(arg,pname,direction,count) in enumerate(params):
  if direction=='v':
   c.append(f'    packet.args[{i}] = {pname};'); call.append(f'p->args[{i}]');continue
  offset=' + '.join(offsets) or '0'
  expr=count
  for j,(_,other,kind,_) in enumerate(params):
   if kind=='v': expr=re.sub(r'\b'+other+r'\b',f'(int)p->args[{j}]',expr)
  if direction=='s':
   c.append(f'    size_t n{i} = {pname} ? strlen((const char *){pname}) + 1 : 1;')
   c.append(f'    n{i} = (n{i} + 1) / 2;')
   v.append(f'        if (!p->counts[{i}] || p->counts[{i}] > 1024 || !memchr(p->data + ({offset}), 0, p->counts[{i}]*2u)) return 0;')
  else:
   c.append(f'    int n{i} = '+ (f'({count}+1)/2;' if direction in ['b','j'] else f'{count};'))
   v.append(f'        if (({expr}) < 0 || p->counts[{i}] != '+(f'(({expr})+1)/2' if direction in ['b','j'] else f'({expr})')+') return 0;')
  c.append(f'    if (n{i} < 0 || (size_t)n{i} > GEM_AES_WORDS-used) '+('return;' if ret=='VOID' else 'return 0;')) if direction!='s' else c.append(f'    if (n{i} > GEM_AES_WORDS-used) '+('return;' if ret=='VOID' else 'return 0;'))
  c.append(f'    packet.counts[{i}] = (uint16_t)n{i};')
  if direction in ['i','s','j']:
   size=f'strlen((const char *){pname})+1' if direction=='s' else (count if direction=='j' else f'(size_t)n{i}*2')
   c.append(f'    if ({pname}) memcpy(packet.data+used, {pname}, {size});')
  d.append(f'        void *arg{i} = p->data + ({offset});')
  offsets.append(f'p->counts[{i}]')
  call.append(f'arg{i}')
  if direction in ['o','b']:
   size = 'strlen((const char *)(packet.data+used))+1' if name in ['shel_read','shel_rdef'] else (count if direction=='b' else f'(size_t)n{i}*2')
   copy.append(f'    if ({pname}) memcpy({pname}, packet.data+used, {size});')
  copy.append(f'    used += packet.counts[{i}];')
  c.append(f'    used += (size_t)n{i};')

 c += ['    (void)used;', '    if (!gem_rpc_call(GEM_RPC_AES_EXT, &packet, sizeof(packet),', '            &result, &packet, sizeof(packet))) '+('return;' if ret=='VOID' else 'return 0;'),'    used = 0;']+copy+['    (void)used;']
 if ret=='WORD':c+=['    return (WORD)result;']
 c+=['}'];client.append('\n'.join(c))
 d += ['        '+('return ' if ret=='WORD' else '')+name+'('+', '.join(call)+');']
 if ret=='VOID':d+=['        return 1;']
 d+=['    }'];server+= '\n'.join(d)+'\n'
 v+=['        return 1;'];valid+='\n'.join(v)+'\n'
for i in range(0,len(client),8):
 (root/f'src/gem/client_aes_{i//8}.c').write_text(notice%'Marshals typed AES scalar, array and string calls.'+'#include "gem_protocol.h"\n#include "gem/gemd.h"\n#include <string.h>\n\n'+'\n\n'.join(client[i:i+8])+'\n')
(root/'src/gemd/aes_dispatch.c').write_text(notice%'Executes validated AES extension calls in the display server.'+'#include "gem/gemd.h"\n#include <stddef.h>\n\nWORD gem_aes_dispatch(gem_aes_packet_t *p)\n{\n    switch(p->function) {\n'+''.join(server)+'    default: return 0;\n    }\n}\n')
s=notice%'Checks each typed AES payload against its public array contract.'+'#include "gem/gemd.h"\n#include <string.h>\n\nint gem_aes_validate(const gem_aes_packet_t *p)\n{\n    size_t used = 0;\n    for (int i=0; i<GEM_AES_ARGS; ++i) {\n        if (p->counts[i] > GEM_AES_WORDS-used) return 0;\n        used += p->counts[i];\n    }\n    switch(p->function) {\n'+''.join(valid)+'    default: return 0;\n    }\n}\n'
draws={'v_pmarker','v_cellarray','v_arc','v_pieslice','v_pie','v_circle','v_ellipse','v_ellarc','v_ellpie','v_rbox','v_rfbox','v_justified','v_contourfill','v_curtext','v_eeos','v_eeol','v_clear_disp_list'}
s+='\nint gem_aes_draws(uint16_t function)\n{\n    switch(function) {\n'+''.join(f'    case rpc_{n}:\n' for _,n,_ in functions if n in draws)+'    default: return 0;\n    }\n}\n'
(root/'src/gem/aes_validate.c').write_text(s)
print('Generated',len(functions),'AES calls')
