/*
 * Checks each typed VDI payload against its public array contract.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem/gemd.h"
#include <string.h>

int gem_vdi_validate(const gem_vdi_packet_t *p)
{
    size_t used = 0;
    for (int i = 0; i < GEM_VDI_ARGS; ++i) {
        if (p->counts[i] > GEM_VDI_WORDS - used)
            return 0;
        used += p->counts[i];
    }
    if (p->args[0] != p->handle)
        return 0;
    switch (p->function) {
        case rpc_v_pmarker:
            if ((2 * (int)p->args[1]) < 0 ||
                p->counts[2] != (2 * (int)p->args[1]))
                return 0;
            return 1;
        case rpc_v_cellarray:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            if (((int)p->args[3] * (int)p->args[4]) < 0 ||
                p->counts[6] != ((int)p->args[3] * (int)p->args[4]))
                return 0;
            return 1;
        case rpc_v_arc:
            return 1;
        case rpc_v_pieslice:
            return 1;
        case rpc_v_pie:
            return 1;
        case rpc_v_circle:
            return 1;
        case rpc_v_ellipse:
            return 1;
        case rpc_v_ellarc:
            return 1;
        case rpc_v_ellpie:
            return 1;
        case rpc_v_rfbox:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            return 1;
        case rpc_v_justified:
            if (!p->counts[3] || p->counts[3] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[3] * 2u))
                return 0;
            return 1;
        case rpc_vst_height:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            return 1;
        case rpc_vst_rotation:
            return 1;
        case rpc_vs_color:
            if ((3) < 0 || p->counts[2] != (3))
                return 0;
            return 1;
        case rpc_vsm_type:
            return 1;
        case rpc_vsm_height:
            return 1;
        case rpc_vsm_color:
            return 1;
        case rpc_vq_color:
            if ((3) < 0 || p->counts[3] != (3))
                return 0;
            return 1;
        case rpc_vq_cellarray:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            if (((int)p->args[3]) < 0 || p->counts[6] != ((int)p->args[3]))
                return 0;
            return 1;
        case rpc_vrq_locator:
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            return 1;
        case rpc_vsm_locator:
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            return 1;
        case rpc_vrq_valuator:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            return 1;
        case rpc_vsm_valuator:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            return 1;
        case rpc_vrq_choice:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            return 1;
        case rpc_vsm_choice:
            if ((1) < 0 || p->counts[1] != (1))
                return 0;
            return 1;
        case rpc_vsin_mode:
            return 1;
        case rpc_vql_attributes:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            return 1;
        case rpc_vqm_attributes:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            return 1;
        case rpc_vqf_attributes:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            return 1;
        case rpc_vqt_attributes:
            if ((6) < 0 || p->counts[1] != (6))
                return 0;
            return 1;
        case rpc_vst_alignment:
            return 1;
        case rpc_vq_extnd:
            if ((57) < 0 || p->counts[2] != (57))
                return 0;
            return 1;
        case rpc_v_contourfill:
            return 1;
        case rpc_vst_background:
            return 1;
        case rpc_vst_effects:
            return 1;
        case rpc_vst_point:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            if ((1) < 0 || p->counts[5] != (1))
                return 0;
            return 1;
        case rpc_vsl_ends:
            return 1;
        case rpc_vsl_end_style:
            return 1;
        case rpc_vsc_form:
            if ((37) < 0 || p->counts[1] != (37))
                return 0;
            return 1;
        case rpc_vsf_udpat:
            if ((16) < 0 || p->counts[1] != (16))
                return 0;
            return 1;
        case rpc_vsl_udsty:
            return 1;
        case rpc_vqin_mode:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            return 1;
        case rpc_vqt_width:
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            return 1;
        case rpc_vst_load_fonts:
            return 1;
        case rpc_vst_unload_fonts:
            return 1;
        case rpc_vq_mouse:
            if ((1) < 0 || p->counts[1] != (1))
                return 0;
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            return 1;
        case rpc_vq_key_s:
            if ((1) < 0 || p->counts[1] != (1))
                return 0;
            return 1;
        case rpc_vqt_name:
            if ((33) < 0 || p->counts[2] != ((33) + 1) / 2)
                return 0;
            return 1;
        case rpc_vq_chcells:
            if ((1) < 0 || p->counts[1] != (1))
                return 0;
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            return 1;
        case rpc_v_exit_cur:
            return 1;
        case rpc_v_enter_cur:
            return 1;
        case rpc_v_curup:
            return 1;
        case rpc_v_curdown:
            return 1;
        case rpc_v_curright:
            return 1;
        case rpc_v_curleft:
            return 1;
        case rpc_v_curhome:
            return 1;
        case rpc_v_eeos:
            return 1;
        case rpc_v_eeol:
            return 1;
        case rpc_vs_curaddress:
            return 1;
        case rpc_v_curtext:
            if (!p->counts[1] || p->counts[1] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[1] * 2u))
                return 0;
            return 1;
        case rpc_v_rvon:
            return 1;
        case rpc_v_rvoff:
            return 1;
        case rpc_vq_curaddress:
            if ((1) < 0 || p->counts[1] != (1))
                return 0;
            if ((1) < 0 || p->counts[2] != (1))
                return 0;
            return 1;
        case rpc_vq_tabstatus:
            return 1;
        case rpc_v_hardcopy:
            return 1;
        case rpc_v_dspcur:
            return 1;
        case rpc_v_rmcur:
            return 1;
        case rpc_v_form_adv:
            return 1;
        case rpc_v_output_window:
            if ((4) < 0 || p->counts[1] != (4))
                return 0;
            return 1;
        case rpc_v_clear_disp_list:
            return 1;
        case rpc_v_bit_image:
            if (!p->counts[1] || p->counts[1] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[1] * 2u))
                return 0;
            if ((4) < 0 || p->counts[7] != (4))
                return 0;
            return 1;
        case rpc_vs_palette:
            return 1;
        case rpc_v_meta_extents:
            return 1;
        case rpc_v_write_meta:
            if (((int)p->args[1]) < 0 || p->counts[2] != ((int)p->args[1]))
                return 0;
            if ((2 * (int)p->args[3]) < 0 ||
                p->counts[4] != (2 * (int)p->args[3]))
                return 0;
            return 1;
        case rpc_vm_filename:
            if (!p->counts[1] || p->counts[1] > 1024 ||
                !memchr(p->data + (0), 0, p->counts[1] * 2u))
                return 0;
            return 1;
        case rpc_v_get_pixel:
            if ((1) < 0 || p->counts[3] != (1))
                return 0;
            if ((1) < 0 || p->counts[4] != (1))
                return 0;
            return 1;
        case rpc_v_escape:
            if (((int)p->args[2]) < 0 || p->counts[4] != ((int)p->args[2]))
                return 0;
            if ((2 * (int)p->args[3]) < 0 ||
                p->counts[5] != (2 * (int)p->args[3]))
                return 0;
            return 1;
        default:
            return 0;
    }
}

int gem_vdi_draws(uint16_t function)
{
    switch (function) {
        case rpc_v_pmarker:
        case rpc_v_cellarray:
        case rpc_v_arc:
        case rpc_v_pieslice:
        case rpc_v_pie:
        case rpc_v_circle:
        case rpc_v_ellipse:
        case rpc_v_ellarc:
        case rpc_v_ellpie:
        case rpc_v_rfbox:
        case rpc_v_justified:
        case rpc_v_contourfill:
        case rpc_v_eeos:
        case rpc_v_eeol:
        case rpc_v_curtext:
        case rpc_v_clear_disp_list:
            return 1;
        default:
            return 0;
    }
}
