/*
 * Executes validated AES extension calls in the display server.
 * Generated by src/gem/generate_aes.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem/gemd.h"
#include <stddef.h>

WORD gem_aes_dispatch(gem_aes_packet_t *p)
{
    switch (p->function) {
        case rpc_appl_find: {
            void *arg0 = p->data + (0);
            return appl_find(arg0);
        }
        case rpc_appl_bvset: {
            return appl_bvset(p->args[0], p->args[1]);
        }
        case rpc_appl_write: {
            void *arg2 = p->data + (0);
            return appl_write(p->args[0], p->args[1], arg2);
        }
        case rpc_appl_read: {
            void *arg2 = p->data + (0);
            return appl_read(p->args[0], p->args[1], arg2);
        }
        case rpc_appl_tplay: {
            void *arg0 = p->data + (0);
            return appl_tplay(arg0, p->args[1], p->args[2]);
        }
        case rpc_appl_trecord: {
            void *arg0 = p->data + (0);
            return appl_trecord(arg0, p->args[1]);
        }
        case rpc_appl_yield: {
            return appl_yield();
        }
        case rpc_evnt_dclick: {
            return evnt_dclick(p->args[0], p->args[1]);
        }
        case rpc_menu_register: {
            void *arg1 = p->data + (0);
            return menu_register(p->args[0], arg1);
        }
        case rpc_menu_unregister: {
            return menu_unregister(p->args[0]);
        }
        case rpc_form_dial: {
            return form_dial(p->args[0], p->args[1], p->args[2], p->args[3],
                             p->args[4], p->args[5], p->args[6], p->args[7],
                             p->args[8]);
        }
        case rpc_form_error: {
            return form_error(p->args[0]);
        }
        case rpc_graf_rubbox: {
            void *arg4 = p->data + (0);
            void *arg5 = p->data + (p->counts[4]);
            return graf_rubbox(p->args[0], p->args[1], p->args[2], p->args[3],
                               arg4, arg5);
        }
        case rpc_graf_dragbox: {
            void *arg8 = p->data + (0);
            void *arg9 = p->data + (p->counts[8]);
            return graf_dragbox(p->args[0], p->args[1], p->args[2], p->args[3],
                                p->args[4], p->args[5], p->args[6], p->args[7],
                                arg8, arg9);
        }
        case rpc_graf_mbox: {
            return graf_mbox(p->args[0], p->args[1], p->args[2], p->args[3],
                             p->args[4], p->args[5]);
        }
        case rpc_graf_growbox: {
            return graf_growbox(p->args[0], p->args[1], p->args[2], p->args[3],
                                p->args[4], p->args[5], p->args[6], p->args[7]);
        }
        case rpc_graf_shrinkbox: {
            return graf_shrinkbox(p->args[0], p->args[1], p->args[2],
                                  p->args[3], p->args[4], p->args[5],
                                  p->args[6], p->args[7]);
        }
        case rpc_scrp_clear: {
            return scrp_clear();
        }
        case rpc_shel_read: {
            void *arg0 = p->data + (0);
            void *arg1 = p->data + (p->counts[0]);
            return shel_read(arg0, arg1);
        }
        case rpc_shel_write: {
            void *arg3 = p->data + (0);
            void *arg4 = p->data + (p->counts[3]);
            return shel_write(p->args[0], p->args[1], p->args[2], arg3, arg4);
        }
        case rpc_shel_get: {
            void *arg0 = p->data + (0);
            return shel_get(arg0, p->args[1]);
        }
        case rpc_shel_put: {
            void *arg0 = p->data + (0);
            return shel_put(arg0, p->args[1]);
        }
        case rpc_shel_rdef: {
            void *arg0 = p->data + (0);
            void *arg1 = p->data + (p->counts[0]);
            return shel_rdef(arg0, arg1);
        }
        case rpc_shel_wdef: {
            void *arg0 = p->data + (0);
            void *arg1 = p->data + (p->counts[0]);
            return shel_wdef(arg0, arg1);
        }
        default:
            return 0;
    }
}
