/*
 * Executes validated VDI extension calls in the display server.
 * Generated by src/gem/generate_vdi.py; edit its schema, then regenerate.
 * All pointer payloads are copied; no application addresses cross RPC.
 *
 * MIT License (see: LICENSE)
 * Copyright (C) 2026 tomaz stih
 */
#include "gem/gemd.h"
#include <stddef.h>

WORD gem_vdi_dispatch(gem_vdi_packet_t *p)
{
    switch (p->function) {
        case rpc_v_pmarker: {
            void *arg2 = p->data + (0);
            v_pmarker(p->args[0], p->args[1], arg2);
            return 1;
        }
        case rpc_v_cellarray: {
            void *arg1 = p->data + (0);
            void *arg6 = p->data + (p->counts[1]);
            return v_cellarray(p->args[0], arg1, p->args[2], p->args[3],
                               p->args[4], p->args[5], arg6);
        }
        case rpc_v_arc: {
            v_arc(p->args[0], p->args[1], p->args[2], p->args[3], p->args[4],
                  p->args[5]);
            return 1;
        }
        case rpc_v_pieslice: {
            v_pieslice(p->args[0], p->args[1], p->args[2], p->args[3],
                       p->args[4], p->args[5]);
            return 1;
        }
        case rpc_v_pie: {
            v_pie(p->args[0], p->args[1], p->args[2], p->args[3], p->args[4],
                  p->args[5]);
            return 1;
        }
        case rpc_v_circle: {
            v_circle(p->args[0], p->args[1], p->args[2], p->args[3]);
            return 1;
        }
        case rpc_v_ellipse: {
            v_ellipse(p->args[0], p->args[1], p->args[2], p->args[3],
                      p->args[4]);
            return 1;
        }
        case rpc_v_ellarc: {
            v_ellarc(p->args[0], p->args[1], p->args[2], p->args[3], p->args[4],
                     p->args[5], p->args[6]);
            return 1;
        }
        case rpc_v_ellpie: {
            v_ellpie(p->args[0], p->args[1], p->args[2], p->args[3], p->args[4],
                     p->args[5], p->args[6]);
            return 1;
        }
        case rpc_v_rfbox: {
            void *arg1 = p->data + (0);
            v_rfbox(p->args[0], arg1);
            return 1;
        }
        case rpc_v_justified: {
            void *arg3 = p->data + (0);
            v_justified(p->args[0], p->args[1], p->args[2], arg3, p->args[4],
                        p->args[5], p->args[6]);
            return 1;
        }
        case rpc_vst_height: {
            void *arg2 = p->data + (0);
            void *arg3 = p->data + (p->counts[2]);
            void *arg4 = p->data + (p->counts[2] + p->counts[3]);
            void *arg5 = p->data + (p->counts[2] + p->counts[3] + p->counts[4]);
            return vst_height(p->args[0], p->args[1], arg2, arg3, arg4, arg5);
        }
        case rpc_vst_rotation: {
            return vst_rotation(p->args[0], p->args[1]);
        }
        case rpc_vs_color: {
            void *arg2 = p->data + (0);
            return vs_color(p->args[0], p->args[1], arg2);
        }
        case rpc_vsm_type: {
            return vsm_type(p->args[0], p->args[1]);
        }
        case rpc_vsm_height: {
            return vsm_height(p->args[0], p->args[1]);
        }
        case rpc_vsm_color: {
            return vsm_color(p->args[0], p->args[1]);
        }
        case rpc_vq_color: {
            void *arg3 = p->data + (0);
            return vq_color(p->args[0], p->args[1], p->args[2], arg3);
        }
        case rpc_vq_cellarray: {
            void *arg1 = p->data + (0);
            void *arg4 = p->data + (p->counts[1]);
            void *arg5 = p->data + (p->counts[1] + p->counts[4]);
            void *arg6 = p->data + (p->counts[1] + p->counts[4] + p->counts[5]);
            return vq_cellarray(p->args[0], arg1, p->args[2], p->args[3], arg4,
                                arg5, arg6);
        }
        case rpc_vrq_locator: {
            void *arg3 = p->data + (0);
            void *arg4 = p->data + (p->counts[3]);
            void *arg5 = p->data + (p->counts[3] + p->counts[4]);
            return vrq_locator(p->args[0], p->args[1], p->args[2], arg3, arg4,
                               arg5);
        }
        case rpc_vsm_locator: {
            void *arg3 = p->data + (0);
            void *arg4 = p->data + (p->counts[3]);
            void *arg5 = p->data + (p->counts[3] + p->counts[4]);
            return vsm_locator(p->args[0], p->args[1], p->args[2], arg3, arg4,
                               arg5);
        }
        case rpc_vrq_valuator: {
            void *arg2 = p->data + (0);
            void *arg3 = p->data + (p->counts[2]);
            return vrq_valuator(p->args[0], p->args[1], arg2, arg3);
        }
        case rpc_vsm_valuator: {
            void *arg2 = p->data + (0);
            void *arg3 = p->data + (p->counts[2]);
            return vsm_valuator(p->args[0], p->args[1], arg2, arg3);
        }
        case rpc_vrq_choice: {
            void *arg2 = p->data + (0);
            return vrq_choice(p->args[0], p->args[1], arg2);
        }
        case rpc_vsm_choice: {
            void *arg1 = p->data + (0);
            return vsm_choice(p->args[0], arg1);
        }
        case rpc_vsin_mode: {
            return vsin_mode(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_vql_attributes: {
            void *arg1 = p->data + (0);
            return vql_attributes(p->args[0], arg1);
        }
        case rpc_vqm_attributes: {
            void *arg1 = p->data + (0);
            return vqm_attributes(p->args[0], arg1);
        }
        case rpc_vqf_attributes: {
            void *arg1 = p->data + (0);
            return vqf_attributes(p->args[0], arg1);
        }
        case rpc_vqt_attributes: {
            void *arg1 = p->data + (0);
            return vqt_attributes(p->args[0], arg1);
        }
        case rpc_vst_alignment: {
            return vst_alignment(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_vq_extnd: {
            void *arg2 = p->data + (0);
            return vq_extnd(p->args[0], p->args[1], arg2);
        }
        case rpc_v_contourfill: {
            v_contourfill(p->args[0], p->args[1], p->args[2], p->args[3]);
            return 1;
        }
        case rpc_vst_background: {
            return vst_background(p->args[0], p->args[1]);
        }
        case rpc_vst_effects: {
            return vst_effects(p->args[0], p->args[1]);
        }
        case rpc_vst_point: {
            void *arg2 = p->data + (0);
            void *arg3 = p->data + (p->counts[2]);
            void *arg4 = p->data + (p->counts[2] + p->counts[3]);
            void *arg5 = p->data + (p->counts[2] + p->counts[3] + p->counts[4]);
            return vst_point(p->args[0], p->args[1], arg2, arg3, arg4, arg5);
        }
        case rpc_vsl_ends: {
            return vsl_ends(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_vsl_end_style: {
            return vsl_end_style(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_vsc_form: {
            void *arg1 = p->data + (0);
            return vsc_form(p->args[0], arg1);
        }
        case rpc_vsf_udpat: {
            void *arg1 = p->data + (0);
            return vsf_udpat(p->args[0], arg1, p->args[2]);
        }
        case rpc_vsl_udsty: {
            return vsl_udsty(p->args[0], p->args[1]);
        }
        case rpc_vqin_mode: {
            void *arg2 = p->data + (0);
            return vqin_mode(p->args[0], p->args[1], arg2);
        }
        case rpc_vqt_width: {
            void *arg2 = p->data + (0);
            void *arg3 = p->data + (p->counts[2]);
            void *arg4 = p->data + (p->counts[2] + p->counts[3]);
            return vqt_width(p->args[0], p->args[1], arg2, arg3, arg4);
        }
        case rpc_vst_load_fonts: {
            return vst_load_fonts(p->args[0], p->args[1]);
        }
        case rpc_vst_unload_fonts: {
            return vst_unload_fonts(p->args[0], p->args[1]);
        }
        case rpc_vq_mouse: {
            void *arg1 = p->data + (0);
            void *arg2 = p->data + (p->counts[1]);
            void *arg3 = p->data + (p->counts[1] + p->counts[2]);
            vq_mouse(p->args[0], arg1, arg2, arg3);
            return 1;
        }
        case rpc_vq_key_s: {
            void *arg1 = p->data + (0);
            return vq_key_s(p->args[0], arg1);
        }
        case rpc_vqt_name: {
            void *arg2 = p->data + (0);
            return vqt_name(p->args[0], p->args[1], arg2);
        }
        case rpc_vq_chcells: {
            void *arg1 = p->data + (0);
            void *arg2 = p->data + (p->counts[1]);
            return vq_chcells(p->args[0], arg1, arg2);
        }
        case rpc_v_exit_cur: {
            return v_exit_cur(p->args[0]);
        }
        case rpc_v_enter_cur: {
            return v_enter_cur(p->args[0]);
        }
        case rpc_v_curup: {
            return v_curup(p->args[0]);
        }
        case rpc_v_curdown: {
            return v_curdown(p->args[0]);
        }
        case rpc_v_curright: {
            return v_curright(p->args[0]);
        }
        case rpc_v_curleft: {
            return v_curleft(p->args[0]);
        }
        case rpc_v_curhome: {
            return v_curhome(p->args[0]);
        }
        case rpc_v_eeos: {
            return v_eeos(p->args[0]);
        }
        case rpc_v_eeol: {
            return v_eeol(p->args[0]);
        }
        case rpc_vs_curaddress: {
            return vs_curaddress(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_v_curtext: {
            void *arg1 = p->data + (0);
            return v_curtext(p->args[0], arg1);
        }
        case rpc_v_rvon: {
            return v_rvon(p->args[0]);
        }
        case rpc_v_rvoff: {
            return v_rvoff(p->args[0]);
        }
        case rpc_vq_curaddress: {
            void *arg1 = p->data + (0);
            void *arg2 = p->data + (p->counts[1]);
            return vq_curaddress(p->args[0], arg1, arg2);
        }
        case rpc_vq_tabstatus: {
            return vq_tabstatus(p->args[0]);
        }
        case rpc_v_hardcopy: {
            return v_hardcopy(p->args[0]);
        }
        case rpc_v_dspcur: {
            return v_dspcur(p->args[0], p->args[1], p->args[2]);
        }
        case rpc_v_rmcur: {
            return v_rmcur(p->args[0]);
        }
        case rpc_v_form_adv: {
            return v_form_adv(p->args[0]);
        }
        case rpc_v_output_window: {
            void *arg1 = p->data + (0);
            return v_output_window(p->args[0], arg1);
        }
        case rpc_v_clear_disp_list: {
            return v_clear_disp_list(p->args[0]);
        }
        case rpc_v_bit_image: {
            void *arg1 = p->data + (0);
            void *arg7 = p->data + (p->counts[1]);
            return v_bit_image(p->args[0], arg1, p->args[2], p->args[3],
                               p->args[4], p->args[5], p->args[6], arg7);
        }
        case rpc_vs_palette: {
            return vs_palette(p->args[0], p->args[1]);
        }
        case rpc_v_meta_extents: {
            return v_meta_extents(p->args[0], p->args[1], p->args[2],
                                  p->args[3], p->args[4]);
        }
        case rpc_v_write_meta: {
            void *arg2 = p->data + (0);
            void *arg4 = p->data + (p->counts[2]);
            return v_write_meta(p->args[0], p->args[1], arg2, p->args[3], arg4);
        }
        case rpc_vm_filename: {
            void *arg1 = p->data + (0);
            return vm_filename(p->args[0], arg1);
        }
        case rpc_v_get_pixel: {
            void *arg3 = p->data + (0);
            void *arg4 = p->data + (p->counts[3]);
            return v_get_pixel(p->args[0], p->args[1], p->args[2], arg3, arg4);
        }
        case rpc_v_escape: {
            void *arg4 = p->data + (0);
            void *arg5 = p->data + (p->counts[4]);
            return v_escape(p->args[0], p->args[1], p->args[2], p->args[3],
                            arg4, arg5);
        }
        default:
            return 0;
    }
}
